### PR TITLE
Use terser to minify

### PR DESCRIPTION
**Pull request by ftsalamp**
In this PR I am using terser to minify the app.js file exported from rollup when building.

### CODE REVIEW

**Comment by vbanos** [comment]
You delete `rollup.config.js`, is this really OK?

**Comment by ftsalamp** [comment]
Yes, it's fine. It was a duplicate file. We are using /config/dev.js for the rollup configuration

**Comment by ftsalamp** [comment]
What's weird is that even though I deleted build/app.js.map in my last commit, it still seems to be causing a conflict.

**Comment by vbanos** [comment]
The files `app.js.map` and `app.js` should be untouched in this PR. That's the only way to avoid a conflict.

**Comment by vbanos** [comment]
Just merged an improvement based on this PR. I'm closing this.

**Pull request closed without merging**
